/**
 * Just Files: the same space as the file tree agents read and write.
 * Left is the tree, right is the selected file exactly as an agent gets it,
 * plus where an edit to it ends up.
 */
import { ArrowUpRightIcon } from "lucide-react";
import { useMemo, useState } from "react";

import ChatMarkdown from "../ChatMarkdown";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import { Toggle, ToggleGroup } from "../ui/toggle-group";
import { buildSpaceFiles, buildTree, fileContent, spaceRoot, type SpacesFile } from "./spacesFiles";
import type { SpacesItemFixture } from "./spacesFixtures";
import { SpacesFileTree } from "./SpacesFileTree";
import { useSpacesNotes } from "./spacesNotes";
import type { Space } from "./spacesSpace";

function writeBackNote(file: SpacesFile): string {
  if (!file.origin) return "Generated by Spaces from the folders around it. Agents can't edit it.";
  if (file.access === "read-only") {
    return `Read-only. Agents can read and quote it; writes are rejected. Change it in ${file.origin}.`;
  }
  if (file.origin === "Spaces") {
    return "A native note. Agent edits save straight into the page, and you see them the next time you open it.";
  }
  return `When an agent saves this file, Executor turns the diff into ${file.origin} API calls. If ${file.origin} changed since the last sync, the agent gets a conflict instead of overwriting it.`;
}

function FilePane(props: {
  file: SpacesFile;
  content: string;
  item: SpacesItemFixture | undefined;
  onOpenItem: (item: SpacesItemFixture) => void;
}) {
  const { file, item } = props;
  const markdown = file.name.endsWith(".md");
  const [mode, setMode] = useState<"source" | "rendered">("source");
  return (
    <section aria-label={file.name} className="flex min-w-0 flex-col">
      <div className="flex flex-wrap items-center gap-2 border-b border-border px-4 py-2.5">
        <code className="min-w-0 flex-1 font-mono text-xs break-all text-foreground">
          {file.path}
        </code>
        {markdown ? (
          <ToggleGroup
            aria-label="Show as"
            value={[mode]}
            onValueChange={(next) => {
              if (next[0] === "source" || next[0] === "rendered") setMode(next[0]);
            }}
          >
            <Toggle value="source">Source</Toggle>
            <Toggle value="rendered">Rendered</Toggle>
          </ToggleGroup>
        ) : null}
      </div>
      <div className="flex flex-wrap items-center gap-2 px-4 pt-3 text-xs text-muted-foreground">
        <Badge variant={file.access === "read-write" ? "success" : "outline"}>
          {file.access === "read-write" ? "Read/write" : "Read-only"}
        </Badge>
        <span>
          {file.origin === undefined
            ? "Generated by Spaces"
            : file.origin === "Spaces"
              ? "Native note in this space"
              : `Synced from ${file.origin} via Executor`}
        </span>
      </div>
      <div className="px-4 py-3">
        {markdown && mode === "rendered" ? (
          <ChatMarkdown text={props.content} cwd={undefined} />
        ) : (
          <pre className="overflow-x-auto rounded-lg bg-muted px-3.5 py-3 font-mono text-xs leading-relaxed whitespace-pre-wrap text-foreground">
            {props.content}
          </pre>
        )}
      </div>
      <div className="flex flex-col items-start gap-2 border-t border-border px-4 py-3">
        <p className="max-w-prose text-xs leading-relaxed text-muted-foreground">
          {writeBackNote(file)}
        </p>
        {item ? (
          <Button size="xs" variant="outline" onClick={() => props.onOpenItem(item)}>
            {item.type === "note" ? "Open page" : "Open preview"}
            <ArrowUpRightIcon />
          </Button>
        ) : null}
      </div>
    </section>
  );
}

export function SpacesAgentView(props: {
  space: Space;
  /** Items in scope after the page's source, kind and search filters. */
  items: readonly SpacesItemFixture[];
  /** Every item in the space, so note links resolve even when filtered out. */
  allItems: readonly SpacesItemFixture[];
  initialItemId: string | undefined;
  onOpenItem: (item: SpacesItemFixture) => void;
}) {
  const { space } = props;
  const notes = useSpacesNotes((state) => state.notes);
  const files = useMemo(() => buildSpaceFiles(space, props.items), [space, props.items]);
  const tree = useMemo(() => buildTree(spaceRoot(space), files), [space, files]);
  const pathOf = useMemo(() => {
    const paths = new Map(
      buildSpaceFiles(space, props.allItems).map((file) => [file.itemId, file.path]),
    );
    return (itemId: string) => paths.get(itemId);
  }, [space, props.allItems]);

  const [selectedPath, setSelectedPath] = useState(
    () =>
      files.find((file) => file.itemId !== undefined && file.itemId === props.initialItemId)
        ?.path ?? `${spaceRoot(space)}/README.md`,
  );
  const selected = files.find((file) => file.path === selectedPath) ?? files[0];
  const item = props.allItems.find((entry) => entry.id === selected?.itemId);

  return (
    <div className="grid overflow-hidden rounded-lg border border-border md:grid-cols-[18rem_minmax(0,1fr)]">
      <div className="border-border max-md:border-b md:border-r">
        <SpacesFileTree
          root={spaceRoot(space)}
          nodes={tree}
          selectedPath={selected?.path}
          onSelect={setSelectedPath}
        />
      </div>
      {selected ? (
        <FilePane
          key={selected.path}
          file={selected}
          content={fileContent(space, selected, props.allItems, notes, pathOf)}
          item={item}
          onOpenItem={props.onOpenItem}
        />
      ) : null}
    </div>
  );
}
