/**
 * PLACEHOLDER DATA. The Plugins page is a UI-only prototype; nothing here is
 * read from Executor, a provider, or the server. Replace these fixtures with
 * real queries once the backend exists, and delete this file.
 */
import type {
  ConnectionAccount,
  ExecutorStatus,
  HarnessId,
  HarnessPlugin,
  Integration,
  IntegrationTool,
  Skill,
} from "./pluginsModel";

const ALL: readonly HarnessId[] = [
  "codex",
  "claudeAgent",
  "cursor",
  "grok",
  "opencode",
  "antigravity",
];

const NORTHWIND = ["northwind"];
const PERSONAL = ["personal"];
const BOTH = ["northwind", "personal"];

const account = (
  id: string,
  label: string,
  identity: string,
  groups: readonly string[],
  extra: Partial<ConnectionAccount> = {},
): ConnectionAccount => ({
  id,
  label,
  identity,
  auth: "connected",
  groups,
  addedBy: "you",
  ...extra,
});

const tools = (...entries: readonly (readonly [string, string])[]): IntegrationTool[] =>
  entries.map(([name, description]) => ({ name, description }));

export const EXECUTOR_STATUS: ExecutorStatus = {
  state: "connected",
  url: "https://executor.example-tailnet.ts.net",
  account: "justyannicc",
  version: "0.9.4",
  lastSync: "2 min ago",
};

export const INTEGRATIONS: readonly Integration[] = [
  {
    id: "github",
    name: "GitHub",
    glyph: "Gh",
    kind: "mcp",
    via: "executor",
    auth: "connected",
    accounts: [account("github-justyannicc", "JustYannicc", "github.com/JustYannicc", BOTH)],
    toolCount: 42,
    tools: tools(
      ["search_issues", "Search issues and pull requests across repositories"],
      ["create_pull_request", "Open a pull request from a branch"],
      ["get_file_contents", "Read a file or directory at a ref"],
      ["list_workflow_runs", "List Actions runs for a workflow"],
    ),
    scopes: ["repo", "read:org", "workflow"],
    harnesses: ALL,
  },
  {
    id: "gmail",
    name: "Gmail",
    glyph: "M",
    kind: "openapi",
    via: "executor",
    auth: "needs-reauth",
    authDetail: "Old Gmail: refresh token expired 9 days ago",
    accounts: [
      account("gmail-work", "Work account", "yannic@northwind.example", NORTHWIND),
      account("gmail-personal", "Personal account", "yannic@personal.example", PERSONAL),
      account("gmail-old", "Old Gmail", "yannic.old@mail.example", PERSONAL, {
        auth: "needs-reauth",
        authDetail: "Refresh token expired 9 days ago",
      }),
    ],
    toolCount: 18,
    tools: tools(
      ["users.messages.list", "List messages matching a query"],
      ["users.messages.get", "Read one message with headers and body"],
      ["users.drafts.create", "Create a draft without sending it"],
    ),
    scopes: ["gmail.readonly", "gmail.compose"],
    harnesses: ALL,
  },
  {
    id: "google-drive",
    name: "Google Drive",
    glyph: "Dr",
    kind: "openapi",
    via: "executor",
    auth: "connected",
    accounts: [
      account("drive-work", "Work drive", "yannic@northwind.example", NORTHWIND),
      account("drive-personal", "Personal drive", "yannic@personal.example", PERSONAL),
    ],
    toolCount: 14,
    tools: tools(
      ["files.list", "Search files and folders"],
      ["files.get", "Read file metadata or export contents"],
    ),
    scopes: ["drive.readonly"],
    harnesses: ALL,
  },
  {
    id: "google-docs",
    name: "Google Docs",
    glyph: "Dc",
    kind: "openapi",
    via: "executor",
    auth: "connected",
    accounts: [account("docs-work", "Work account", "yannic@northwind.example", NORTHWIND)],
    toolCount: 9,
    tools: tools(
      ["documents.get", "Read a document's structure and text"],
      ["documents.batchUpdate", "Apply edits to a document"],
    ),
    scopes: ["documents"],
    harnesses: ["codex", "claudeAgent"],
  },
  {
    id: "google-sheets",
    name: "Google Sheets",
    glyph: "Sh",
    kind: "openapi",
    via: "executor",
    auth: "connected",
    accounts: [
      account("sheets-work", "Work account", "yannic@northwind.example", NORTHWIND),
      account("sheets-personal", "Personal account", "yannic@personal.example", PERSONAL),
    ],
    toolCount: 11,
    tools: tools(
      ["spreadsheets.values.get", "Read a cell range"],
      ["spreadsheets.values.update", "Write values into a range"],
    ),
    scopes: ["spreadsheets"],
    harnesses: ["codex", "claudeAgent"],
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    glyph: "Ca",
    kind: "openapi",
    via: "executor",
    auth: "needs-reauth",
    authDetail: "Work calendar: refresh token expired 3 days ago",
    accounts: [
      account("calendar-work", "Work calendar", "yannic@northwind.example", NORTHWIND, {
        auth: "needs-reauth",
        authDetail: "Refresh token expired 3 days ago",
      }),
      account("calendar-personal", "Personal calendar", "yannic@personal.example", PERSONAL),
    ],
    toolCount: 12,
    tools: tools(
      ["events.list", "List events in a time window"],
      ["events.insert", "Create an event"],
      ["freebusy.query", "Check availability across calendars"],
    ),
    scopes: ["calendar.events"],
    harnesses: ALL,
  },
  {
    id: "notion",
    name: "Notion",
    glyph: "N",
    kind: "mcp",
    via: "executor",
    auth: "connected",
    accounts: [
      account("notion-personal", "Yannic's workspace", "yannic@personal.example", PERSONAL),
    ],
    toolCount: 16,
    tools: tools(
      ["search", "Search pages and databases"],
      ["fetch_page", "Read a page as markdown"],
      ["update_page", "Append or replace page content"],
    ),
    scopes: ["read_content", "update_content"],
    harnesses: ALL,
  },
  {
    id: "slack",
    name: "Slack",
    glyph: "Sl",
    kind: "mcp",
    via: "executor",
    auth: "connected",
    accounts: [
      account("slack-northwind", "Northwind workspace", "northwind-pay.slack.com", NORTHWIND, {
        addedBy: "admins",
      }),
    ],
    toolCount: 21,
    tools: tools(
      ["search_messages", "Search messages the account can see"],
      ["post_message", "Post to a channel or thread"],
      ["read_thread", "Read replies in a thread"],
    ),
    scopes: ["search:read", "chat:write", "channels:history"],
    harnesses: ["codex", "claudeAgent"],
  },
  {
    id: "jira",
    name: "Jira",
    glyph: "J",
    kind: "openapi",
    via: "executor",
    auth: "connected",
    accounts: [
      account("jira-northwind", "Northwind Jira", "northwind-pay.atlassian.net", NORTHWIND, {
        addedBy: "admins",
      }),
    ],
    toolCount: 27,
    tools: tools(
      ["searchForIssuesUsingJql", "Search issues with JQL"],
      ["createIssue", "Create an issue"],
      ["transitionIssue", "Move an issue to another status"],
    ),
    scopes: ["read:jira-work", "write:jira-work"],
    harnesses: ALL,
  },
  {
    id: "confluence",
    name: "Confluence",
    glyph: "Co",
    kind: "openapi",
    via: "executor",
    auth: "connected",
    accounts: [
      account("confluence-northwind", "Northwind wiki", "northwind-pay.atlassian.net", NORTHWIND, {
        addedBy: "admins",
      }),
    ],
    toolCount: 19,
    tools: tools(["searchContent", "Search pages with CQL"], ["getPageById", "Read a page body"]),
    scopes: ["read:confluence-content.all"],
    harnesses: ALL,
  },
  {
    id: "sentry",
    name: "Sentry",
    glyph: "Se",
    kind: "mcp",
    via: "executor",
    auth: "error",
    authDetail: "sentry.io returned 401: token revoked",
    accounts: [
      account("sentry-northwind", "Northwind Sentry", "northwind-pay.sentry.io", NORTHWIND, {
        addedBy: "admins",
        auth: "error",
        authDetail: "sentry.io returned 401: token revoked",
      }),
    ],
    toolCount: 14,
    tools: tools(
      ["search_issues", "Find issues by query"],
      ["get_issue_details", "Read an issue with its latest event"],
    ),
    scopes: ["event:read", "project:read"],
    harnesses: ALL,
  },
  {
    id: "vercel",
    name: "Vercel",
    glyph: "▲",
    kind: "openapi",
    via: "executor",
    auth: "connected",
    accounts: [account("vercel-personal", "Personal team", "justyannicc", PERSONAL)],
    toolCount: 23,
    tools: tools(
      ["listDeployments", "List deployments for a project"],
      ["getDeploymentEvents", "Read build logs"],
    ),
    scopes: ["deployments:read", "projects:read"],
    harnesses: ALL,
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    glyph: "Cf",
    kind: "openapi",
    via: "executor",
    auth: "connected",
    accounts: [
      account("cloudflare-personal", "Yannic's account", "yannic@personal.example", PERSONAL),
    ],
    toolCount: 58,
    tools: tools(
      ["zones.list", "List zones"],
      ["dns-records.create", "Create a DNS record"],
      ["workers.scripts.list", "List Workers scripts"],
    ),
    scopes: ["zone:read", "dns:edit", "workers:read"],
    harnesses: ["codex", "claudeAgent"],
  },
  {
    id: "linear",
    name: "Linear",
    glyph: "Li",
    kind: "graphql",
    via: "executor",
    auth: "connected",
    accounts: [account("linear-t3", "T3 Tools", "t3tools.linear.app", PERSONAL)],
    toolCount: 31,
    tools: tools(["issues", "Query issues with filters"], ["issueCreate", "Create an issue"]),
    scopes: ["read", "write"],
    harnesses: ALL,
  },
  {
    id: "todoist",
    name: "Todoist",
    glyph: "Td",
    kind: "openapi",
    via: "executor",
    auth: "connected",
    accounts: [account("todoist-personal", "Personal tasks", "yannic@personal.example", PERSONAL)],
    toolCount: 12,
    tools: tools(["getTasks", "List active tasks"], ["createTask", "Add a task"]),
    scopes: ["data:read_write"],
    harnesses: ["claudeAgent"],
  },
  {
    id: "trello",
    name: "Trello",
    glyph: "Tr",
    kind: "openapi",
    via: "executor",
    auth: "needs-reauth",
    authDetail: "Token was granted for 30 days and has expired",
    accounts: [
      account("trello-personal", "Personal boards", "yannic@personal.example", PERSONAL, {
        auth: "needs-reauth",
        authDetail: "Token was granted for 30 days and has expired",
      }),
    ],
    toolCount: 15,
    tools: tools(["getBoards", "List boards"], ["createCard", "Add a card to a list"]),
    scopes: ["read", "write"],
    harnesses: ["claudeAgent"],
  },
  {
    id: "raindrop",
    name: "Raindrop",
    glyph: "Rd",
    kind: "openapi",
    via: "executor",
    auth: "connected",
    accounts: [account("raindrop-personal", "Bookmarks", "yannic@personal.example", PERSONAL)],
    toolCount: 8,
    tools: tools(["getRaindrops", "List bookmarks in a collection"]),
    scopes: ["read"],
    harnesses: ["codex"],
  },
  {
    id: "spotify",
    name: "Spotify",
    glyph: "Sp",
    kind: "openapi",
    via: "executor",
    auth: "connected",
    accounts: [account("spotify-personal", "Personal", "yannic@personal.example", PERSONAL)],
    toolCount: 17,
    tools: tools(["getCurrentlyPlaying", "Read the playing track"], ["pause", "Pause playback"]),
    scopes: ["user-read-playback-state", "user-modify-playback-state"],
    harnesses: [],
  },
  {
    id: "playwright",
    name: "Playwright",
    glyph: "Pw",
    kind: "mcp",
    via: "direct",
    transport: "stdio",
    auth: "none",
    accounts: [],
    groups: BOTH,
    toolCount: 21,
    tools: tools(
      ["browser_navigate", "Open a URL in the controlled browser"],
      ["browser_snapshot", "Read the page's accessibility tree"],
    ),
    scopes: [],
    harnesses: ["codex", "claudeAgent"],
  },
  {
    id: "chrome-devtools",
    name: "Chrome DevTools",
    glyph: "Dt",
    kind: "mcp",
    via: "direct",
    transport: "stdio",
    auth: "none",
    accounts: [],
    groups: BOTH,
    toolCount: 26,
    tools: tools(["performance_start_trace", "Record a performance trace"]),
    scopes: [],
    harnesses: ["codex"],
  },
  {
    id: "context7",
    name: "Context7",
    glyph: "C7",
    kind: "mcp",
    via: "direct",
    transport: "http",
    auth: "error",
    authDetail: "Server unreachable at mcp.context7.com",
    accounts: [],
    groups: PERSONAL,
    toolCount: 2,
    tools: tools(["resolve-library-id", "Find a library's docs id"]),
    scopes: [],
    harnesses: ["cursor"],
  },
];

export const HARNESS_PLUGINS: readonly HarnessPlugin[] = [
  {
    id: "codex-browser",
    harness: "codex",
    name: "browser-use",
    version: "0.4.2",
    description: "Drives a headless browser for web tasks.",
    source: "openai-curated",
    enabled: true,

    groups: BOTH,
  },
  {
    id: "codex-figma",
    harness: "codex",
    name: "figma",
    version: "1.2.0",
    description: "Reads frames and variables from Figma files.",
    source: "openai-curated",
    enabled: true,
    updateAvailable: "1.3.0",

    groups: NORTHWIND,
  },
  {
    id: "codex-plugin-creator",
    harness: "codex",
    name: "plugin-creator",
    version: "0.2.1",
    description: "Scaffolds new Codex plugins and marketplace entries.",
    source: "personal",
    enabled: false,

    groups: PERSONAL,
  },
  {
    id: "claude-code-review",
    harness: "claudeAgent",
    name: "code-review",
    version: "1.0.3",
    description: "Adds /code-review with parallel standards and spec reviewers.",
    source: "claude-plugins-official",
    enabled: true,

    groups: BOTH,
  },
  {
    id: "claude-commit-commands",
    harness: "claudeAgent",
    name: "commit-commands",
    version: "1.1.0",
    description: "Commit, push, and open PRs from slash commands.",
    source: "claude-plugins-official",
    enabled: true,

    groups: BOTH,
  },
  {
    id: "claude-frontend-design",
    harness: "claudeAgent",
    name: "frontend-design",
    version: "0.9.1",
    description: "Design guidance and review for UI work.",
    source: "claude-plugins-official",
    enabled: false,

    groups: PERSONAL,
  },
];

export const SKILLS: readonly Skill[] = [
  {
    id: "diagnosing-bugs",
    name: "diagnosing-bugs",
    description: "Diagnosis loop for hard bugs and performance regressions.",
    source: "personal",
    harnesses: ["codex", "claudeAgent", "opencode"],

    groups: BOTH,
  },
  {
    id: "effect-v4",
    name: "effect-v4",
    description: "Effect v4 patterns and v3 migration guidance.",
    source: "personal",
    harnesses: ["codex", "claudeAgent"],

    groups: BOTH,
  },
  {
    id: "impeccable",
    name: "impeccable",
    description: "Design, critique, and polish frontend interfaces.",
    source: "personal",
    harnesses: ["codex", "claudeAgent", "cursor"],

    groups: BOTH,
  },
  {
    id: "test-t3-app",
    name: "test-t3-app",
    description: "Verify Signalbox's web UI in the built-in browser panel.",
    source: "project",
    origin: "t3code",
    harnesses: ["codex", "claudeAgent"],

    groups: PERSONAL,
  },
  {
    id: "test-t3-mobile",
    name: "test-t3-mobile",
    description: "Verify the native app through the Device panel.",
    source: "project",
    origin: "t3code",
    harnesses: ["codex", "claudeAgent"],

    groups: PERSONAL,
  },
  {
    id: "writing-for-agents",
    name: "writing-for-agents",
    description: "Write skills, AGENTS.md, and other agent instructions.",
    source: "personal",
    harnesses: ALL,

    groups: BOTH,
  },
  {
    id: "babysit-pr",
    name: "babysit-pr",
    description: "Watch a PR's checks and reviews until it merges.",
    source: "plugin",
    origin: "commit-commands",
    harnesses: ["claudeAgent"],

    groups: NORTHWIND,
  },
  {
    id: "plugin-creator",
    name: "plugin-creator",
    description: "Scaffold Codex plugins with a valid manifest.",
    source: "plugin",
    origin: "plugin-creator",
    harnesses: ["codex"],

    groups: PERSONAL,
  },
  {
    id: "tdd",
    name: "tdd",
    description: "Red-green-refactor, one behavior at a time.",
    source: "personal",
    harnesses: [],

    groups: PERSONAL,
  },
  {
    id: "dataviz",
    name: "dataviz",
    description: "Charts and dashboards that read as one system.",
    source: "plugin",
    origin: "frontend-design",
    harnesses: ["claudeAgent", "opencode"],

    groups: PERSONAL,
  },
  {
    id: "find-skills",
    name: "find-skills",
    description: "Find and install skills for the task in front of you.",
    source: "skills.sh",
    origin: "vercel-labs/skills",
    harnesses: ALL,
    groups: BOTH,
  },
  {
    id: "remotion-best-practices",
    name: "remotion-best-practices",
    description: "Compositions, timing, and rendering with Remotion.",
    source: "skills.sh",
    origin: "remotion-dev/skills",
    harnesses: ["claudeAgent"],
    groups: PERSONAL,
  },
  {
    id: "northwind-terminal",
    name: "northwind-terminal",
    description: "Neptune APIs and PAX terminal rules for Northwind payment work.",
    source: "skills.sh",
    origin: "northwind/agent-skills",
    harnesses: ["codex", "claudeAgent"],
    groups: NORTHWIND,
  },
  {
    id: "northwind-expenses",
    name: "northwind-expenses",
    description: "File monthly expenses with the company Expense agent.",
    source: "team",
    origin: "Flynn",
    harnesses: ["codex", "claudeAgent"],
    groups: NORTHWIND,
  },
  {
    id: "customer-email-triage",
    name: "customer-email-triage",
    description: "Sort customer email and draft replies for approval.",
    source: "team",
    origin: "you",
    harnesses: ["codex", "claudeAgent", "opencode"],
    groups: NORTHWIND,
  },
];
